- update to 1.5.22

diff --git a/mutt-forcedotlock.patch b/mutt-forcedotlock.patch
--- a/mutt-forcedotlock.patch
+++ b/mutt-forcedotlock.patch
@@ -1,6 +1,6 @@
 --- mutt-1.5.15/Makefile.am.orig	2007-06-03 12:32:52.028633000 +0200
 +++ mutt-1.5.15/Makefile.am	2007-06-03 13:05:48.801283592 +0200
-@@ -138,9 +138,9 @@
+@@ -154,9 +154,9 @@
  		rm -f $(DESTDIR)$(bindir)/mutt.dotlock ;		\
  		ln -sf $(DESTDIR)$(bindir)/mutt_dotlock $(DESTDIR)$(bindir)/mutt.dotlock ; \
  	fi
@@ -10,6 +10,6 @@
 +	if test -f $(DESTDIR)$(bindir)/mutt_dotlock && test x$(DOTLOCK_GROUP) != x ; then \
 +		chgrp $(DOTLOCK_GROUP) $(DESTDIR)$(bindir)/mutt_dotlock && \
 +		chmod $(DOTLOCK_PERMISSION) $(DESTDIR)$(bindir)/mutt_dotlock || \
- 		{ echo "Can't fix mutt_dotlock's permissions!" >&2 ; exit 1 ; } \
+ 		{ echo "Can't fix mutt_dotlock's permissions!  This is required to lock mailboxes in the mail spool directory." >&2 ; exit 1 ; } \
  	fi
  
